export { MainLayout as default } from './layouts'
export { Logo } from './logo'
export { Fonts } from './fonts'
export { Section } from './section/index'
export { BioSection, BioYear } from './bio/styles/bio'
